### ISSUE TITLE
Only 3 comparison websites are included

### ISSUE THREAD

**Issue by AditiB24** [07Neo/PricePilot#1]

**Comment by AditiB24** [comment]
I've added Croma website's data for better comparison

**Comment by atharvaambike** [comment]
Thank you, @AditiB24 ! 
Your contribution of adding the new website for scraping and comparison has greatly improved the project. 
This addition will help streamline the process and make data analysis more efficient. 
Your efforts are truly appreciated!

Happy coding!!
