### ISSUE TITLE
Add Readme file

### ISSUE THREAD

**Issue by atharvaambike** [07Neo/PricePilot#2]

**Comment by SaeeBiwalkar** [comment]
I would like to work on Readme file, I am good at documentation, Kindly allow me

**Comment by atharvaambike** [comment]
Yes, write about the website and its working in brief.

**Comment by atharvaambike** [comment]
Thank you, @SaeeBiwalkar ! You're the first contributor to this project, and your efforts in adding the README have significantly improved it. 

Your contribution has made a real difference by helping readers understand the project more clearly!

Happy contributing!!
